build_settings:
  ignore:
    - ./vendor
    - ./tests
    - ./docs
    - ./build
    - ./_compiled
  allowed_warnings: -1

setup:
  env:
    PHAN_ALLOW_XDEBUG: true

  composer:
    action: install

test:
  pdepend:
    directory: ./src

  php_code_sniffer:
    standard: PSR2
    allowed_errors: 0

  php_cpd:
    directory: ./src

  php_docblock_checker:
    directory: ./src
    allowed_warnings: 20

  php_loc:
    directory: ./src

  php_mess_detector:
    directory: ./src
    rules:
      - cleancode
      - controversial
      - codesize
      - design
      - naming
      - unusedcode

  php_parallel_lint:
    directory: ./src

  php_unit:
    config:
      - phpunit.xml.dist
    directories:
      - tests
    coverage: true

  security_checker: ~

  technical_debt:
    directory: ./src
    allowed_errors: 2

#deploy:
#  mage3:
#    env: production

success:
  slack_notify:
    webhook_url: "https://hooks.slack.com/services/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"
    room: "#taiga"
    username: "PHP Censor"
    icon: ":ghost:"
    message: "%PROJECT_TITLE% - build %BUILD% succeeded! :smiley:"
    show_status: false


failure:
  slack_notify:
    webhook_url: "https://hooks.slack.com/services/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"
    room: "#taiga"
    username: "PHP Censor"
    icon: ":ghost:"
    message: "%PROJECT_TITLE% - build %BUILD% failed! :sleepy:"
    show_status: false

complete:
  slack_notify:
    webhook_url: "https://hooks.slack.com/services/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"
    room: "#taiga"
    username: "PHP Censor"
    icon: ":ghost:"
    message: "%PROJECT_TITLE% - build %BUILD% finished."
    show_status: true

  email:
    committer: true
    default_mailto_address: "panosru@me.com"
